apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "backend-sa" .Values.backendServiceAccount }}
  annotations:
    {{- if .Capabilities.APIVersions.Has "cloud.google.com/v1" }}
    iam.gke.io/gcp-service-account: {{ default "placeholder@gserviceaccount.com" .Values.workloadIdentityServiceAccountEmail }}
    {{- end }}
