apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
    role: backend
  annotations:
    {{- if .Capabilities.APIVersions.Has "cloud.google.com/v1" }}
    cloud.google.com/backend-config: '{"default": "backend-http-hc-config"}'
    {{- end }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    role: backend