apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ default 2 .Values.replicaCountFrontend }}
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: {{ .Values.frontendImage.registry }}/{{ .Values.backendImage.repository }}:{{ .Values.frontendImage.tag }}
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - containerPort: 80
      restartPolicy: Always
