name: Release Helm Chart

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Package Chart
        run: mkdir -p dist && helm package ./todoapp -d dist

      - name: Generate Changelog
        run: echo "# Update TodoApp Helm Chart ${GITHUB_REF#refs/tags/}" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: dist/*

      - name: Trigger Index Helm Chart Workflow
        run: |
          gh workflow run index_helm_charts.yaml --repo p-le/devops-helm-charts
