name: Release Helm Chart (Manually)

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Package Chart
        run: mkdir -p dist && helm package ./todoapp -d dist

      - name: Generate Changelog
        run: echo "# Update TodoApp Helm Chart ${GITHUB_REF#refs/tags/}" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: dist/*
